import 'package:exceptiontest/exceptiontest.dart' as exceptiontest;

void main(List<String> arguments) {
  print('Hello world: ${exceptiontest.calculate()}!');
}
